apiVersion: apps/v1
kind: Deployment
metadata:
  name: manuscriptmanage
  labels:
    app: manuscriptmanage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manuscriptmanage
  template:
    metadata:
      labels:
        app: manuscriptmanage
    spec:
      containers:
        - name: manuscriptmanage
          image: "username/manuscriptmanage:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
