server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: authorenroll
          uri: http://localhost:8082
          predicates:
            - Path=/writers/**, /enrollViews/**
        - id: manuscriptmanage
          uri: http://localhost:8083
          predicates:
            - Path=/publishScripts/**, /writeViews/**
        - id: aiservice
          uri: http://localhost:8084
          predicates:
            - Path=/services/**, 
        - id: authentication
          uri: http://localhost:8085
          predicates:
            - Path=/users/**, /userViews/**
        - id: mybooklist
          uri: http://localhost:8086
          predicates:
            - Path=/books/**, /bookViews/**
        - id: point
          uri: http://localhost:8087
          predicates:
            - Path=/points/**, /pointViews/**
        - id: payment
          uri: http://localhost:8088
          predicates:
            - Path=/payments/**, /paymentViews/**
        - id: publish
          uri: http://localhost:8089
          predicates:
            - Path=/publishBooks/**, /publishbookViews/**
        - id: notification
          uri: http://localhost:8090
          predicates:
            - Path=/알림/**, /alertViews/**
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: authorenroll
          uri: http://authorenroll:8080
          predicates:
            - Path=/writers/**, 
        - id: manuscriptmanage
          uri: http://manuscriptmanage:8080
          predicates:
            - Path=/publishScripts/**, 
        - id: aiservice
          uri: http://aiservice:8080
          predicates:
            - Path=/services/**, 
        - id: authentication
          uri: http://authentication:8080
          predicates:
            - Path=/users/**, 
        - id: mybooklist
          uri: http://mybooklist:8080
          predicates:
            - Path=/books/**, 
        - id: point
          uri: http://point:8080
          predicates:
            - Path=/points/**, 
        - id: payment
          uri: http://payment:8080
          predicates:
            - Path=/payments/**, 
        - id: publish
          uri: http://publish:8080
          predicates:
            - Path=/publishBooks/**, 
        - id: notification
          uri: http://notification:8080
          predicates:
            - Path=/알림/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
