apiVersion: apps/v1
kind: Deployment
metadata:
  name: authorenroll
  labels:
    app: authorenroll
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authorenroll
  template:
    metadata:
      labels:
        app: authorenroll
    spec:
      containers:
        - name: authorenroll
          image: "username/authorenroll:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
